"""Pure formatter: reads a findings.json file (produced in-session, not by
this script — see README.md) and renders it as a JSON summary + a
self-contained HTML dashboard. Makes no assessment judgments and no API
calls; the crosswalk table / gap matrix / verdict / remediation-paths shape
follows AAS-DO178-Demo's DO-330 case study, and the HTML theme reuses
ai-security/harness/generate_html_report.py's dark "security terminal" style
for visual consistency with its sibling project.

Usage:
    python report.py <subject>          # e.g. python report.py portfolio-sync
"""

import argparse
import html
import json
from datetime import datetime, timezone
from pathlib import Path

from controls import controls_by_id

REPO_ROOT = Path(__file__).resolve().parent
FINDINGS_DIR = REPO_ROOT / "findings"
REPORTS_DIR = REPO_ROOT / "reports"

COVERAGE_META = {
    "Met": {"color": "#22c55e", "bg": "rgba(34,197,94,0.12)"},
    "Partial": {"color": "#f59e0b", "bg": "rgba(245,158,11,0.14)"},
    "Gap": {"color": "#ef4444", "bg": "rgba(239,68,68,0.14)"},
}


def load_findings(subject: str) -> dict:
    path = FINDINGS_DIR / f"{subject}-findings.json"
    if not path.exists():
        raise FileNotFoundError(
            f"No findings file for '{subject}' at {path}. Findings are written "
            "in-session (see README.md), not generated by this script."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def compute_summary(findings: list[dict]) -> dict:
    counts = {"Met": 0, "Partial": 0, "Gap": 0}
    flagged = 0
    for f in findings:
        counts[f["coverage"]] += 1
        if f.get("needs_human_review"):
            flagged += 1
    return {**counts, "total": len(findings), "needs_human_review": flagged}


def verdict_text(summary: dict) -> str:
    if summary["Gap"] == 0 and summary["needs_human_review"] == 0:
        return (
            "No outright gaps found, and every verdict was reached with high "
            "enough confidence to stand without a human re-check. Partial "
            "coverage still means real work remains before this would satisfy "
            "a formal conformity assessment."
        )
    parts = []
    if summary["Gap"]:
        parts.append(f"{summary['Gap']} control(s) have no real coverage yet")
    if summary["needs_human_review"]:
        parts.append(
            f"{summary['needs_human_review']} finding(s) are flagged for human "
            "review rather than treated as settled"
        )
    return "; ".join(parts) + "."


def remediation_paths(findings: list[dict], controls: dict) -> list[str]:
    paths = []
    for f in findings:
        if f["coverage"] == "Gap":
            title = controls[f["control_id"]]["title"]
            paths.append(f"Close the gap on {title} ({f['control_id']}) — currently no real coverage.")
        elif f.get("needs_human_review"):
            title = controls[f["control_id"]]["title"]
            reason = f.get("human_review_reason", "flagged low-confidence verdict")
            paths.append(f"Resolve open question on {title} ({f['control_id']}): {reason}")
    if not paths:
        paths.append("No outstanding gaps or flagged findings — next step is periodic re-assessment, not remediation.")
    return paths


def render_finding_row(f: dict, controls: dict) -> str:
    control = controls[f["control_id"]]
    meta = COVERAGE_META[f["coverage"]]
    flag_html = ""
    if f.get("needs_human_review"):
        flag_html = (
            f'<div class="flag">NEEDS HUMAN REVIEW — {html.escape(f.get("human_review_reason", ""))}</div>'
        )
    return f"""
    <details class="card">
      <summary>
        <span class="badge" style="color:{meta['color']};background:{meta['bg']}">{f['coverage']}</span>
        <span class="control-id">{html.escape(f['control_id'])}</span>
        <span class="control-title">{html.escape(control['title'])}</span>
        <span class="framework-pill">{html.escape(control['framework'])}</span>
      </summary>
      <div class="card-body">
        <div class="field"><span class="field-label">What would satisfy this</span>{html.escape(control['what_would_satisfy_this'].strip())}</div>
        <div class="field"><span class="field-label">Rationale</span>{html.escape(f['rationale'])}</div>
        <div class="field"><span class="field-label">Confidence</span>{html.escape(f['confidence'])}</div>
        {flag_html}
      </div>
    </details>
    """


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AI Compliance Crosswalk — {subject}</title>
<style>
  :root{{
    --bg:#0a0d10; --panel:#11161b; --panel-2:#161c22;
    --ink:#e8eaed; --ink-2:#9aa4ae; --ink-faint:#5b6570;
    --accent:#2dd4bf; --rule:#232a31;
    --mono: Consolas,'SF Mono','Cascadia Code','Courier New',monospace;
    --sans: 'Segoe UI',system-ui,-apple-system,sans-serif;
  }}
  *{{box-sizing:border-box}}
  html,body{{margin:0;padding:0;background:var(--bg)}}
  body{{color:var(--ink);font-family:var(--sans);line-height:1.5;padding:32px 20px 80px}}
  .page{{max-width:920px;margin:0 auto}}
  h1{{font-size:22px;font-weight:600;margin:0 0 4px;color:var(--ink)}}
  .subtitle{{font-family:var(--mono);font-size:12px;color:var(--ink-faint);margin-bottom:28px}}
  h2{{font-size:17px;font-weight:600;color:var(--accent);margin:0 0 14px}}
  section{{margin-bottom:36px}}
  .stat-row{{display:flex;gap:12px;margin-bottom:20px}}
  .stat{{flex:1;background:var(--panel);border:1px solid;border-radius:8px;padding:14px;display:flex;flex-direction:column;gap:2px}}
  .stat-num{{font-family:var(--mono);font-size:26px;font-weight:700;color:var(--ink)}}
  .stat-label{{font-family:var(--mono);font-size:10px;letter-spacing:0.08em;color:var(--ink-faint)}}
  .cards{{display:flex;flex-direction:column;gap:8px}}
  .card{{background:var(--panel);border:1px solid var(--rule);border-radius:8px;overflow:hidden}}
  .card[open]{{border-color:#334049}}
  .card summary{{
    list-style:none;cursor:pointer;padding:12px 14px;display:flex;align-items:center;gap:10px;
    font-family:var(--mono);font-size:12.5px;
  }}
  .card summary::-webkit-details-marker{{display:none}}
  .card summary:hover{{background:var(--panel-2)}}
  .badge{{font-weight:700;font-size:10.5px;letter-spacing:0.05em;padding:3px 8px;border-radius:5px;flex-shrink:0}}
  .control-id{{color:var(--ink);font-weight:600;flex-shrink:0}}
  .control-title{{color:var(--ink-2);flex:1}}
  .framework-pill{{color:var(--ink-faint);font-size:10.5px;border:1px solid var(--rule);padding:2px 7px;border-radius:20px}}
  .card-body{{padding:4px 14px 16px;border-top:1px solid var(--rule)}}
  .field{{margin-top:12px;font-size:13.5px;color:var(--ink)}}
  .field-label{{display:block;font-family:var(--mono);font-size:10px;letter-spacing:0.06em;color:var(--ink-faint);margin-bottom:4px;text-transform:uppercase}}
  .flag{{margin-top:12px;padding:8px 12px;border-left:3px solid #f59e0b;background:var(--panel-2);border-radius:0 6px 6px 0;font-size:12.5px;color:#f59e0b;font-family:var(--mono)}}
  .verdict{{background:var(--panel);border:1px solid var(--rule);border-radius:8px;padding:16px;font-size:14px}}
  .remediation{{background:var(--panel);border:1px solid var(--rule);border-radius:8px;padding:16px 16px 16px 32px;font-size:13.5px}}
  .remediation li{{margin-bottom:8px}}
  .footer-note{{margin-top:40px;padding-top:16px;border-top:1px solid var(--rule);font-size:11.5px;color:var(--ink-faint);font-family:var(--mono)}}
</style>
</head>
<body>
<div class="page">
  <h1>AI Compliance Crosswalk — {subject}</h1>
  <div class="subtitle">Assessed {assessed_at} · {assessed_by}</div>

  <section>
    <div class="stat-row">
      <div class="stat" style="border-color:#22c55e"><span class="stat-num" style="color:#22c55e">{met}</span><span class="stat-label">MET</span></div>
      <div class="stat" style="border-color:#f59e0b"><span class="stat-num" style="color:#f59e0b">{partial}</span><span class="stat-label">PARTIAL</span></div>
      <div class="stat" style="border-color:#ef4444"><span class="stat-num" style="color:#ef4444">{gap}</span><span class="stat-label">GAP</span></div>
      <div class="stat" style="border-color:#4b5563"><span class="stat-num">{total}</span><span class="stat-label">TOTAL</span></div>
    </div>
  </section>

  <section>
    <h2>Crosswalk</h2>
    <div class="cards">
      {cards}
    </div>
  </section>

  <section>
    <h2>Verdict</h2>
    <div class="verdict">{verdict}</div>
  </section>

  <section>
    <h2>Remediation Paths</h2>
    <ol class="remediation">
      {remediation_items}
    </ol>
  </section>

  <div class="footer-note">
    Coverage verdicts were reached in-session by Claude reading each control
    against real evidence (system prompt, red-team report, governance notes),
    not by keyword matching or a scripted API call — see PROMPT_INPUTS.md and
    README.md in this project for methodology. This is a self-assessment, not
    an external conformity assessment.
  </div>
</div>
</body>
</html>
"""


def render_html(subject: str, findings_data: dict, controls: dict) -> str:
    findings = findings_data["findings"]
    summary = compute_summary(findings)
    cards = "\n".join(render_finding_row(f, controls) for f in findings)
    remediation_items = "\n".join(f"<li>{html.escape(p)}</li>" for p in remediation_paths(findings, controls))
    return PAGE_TEMPLATE.format(
        subject=html.escape(subject),
        assessed_at=html.escape(findings_data.get("assessed_at_utc", "unknown")),
        assessed_by=html.escape(findings_data.get("assessed_by", "unknown")),
        met=summary["Met"],
        partial=summary["Partial"],
        gap=summary["Gap"],
        total=summary["total"],
        cards=cards,
        verdict=html.escape(verdict_text(summary)),
        remediation_items=remediation_items,
    )


def write_report(subject: str) -> tuple[Path, Path]:
    findings_data = load_findings(subject)
    controls = controls_by_id()

    unknown = [f["control_id"] for f in findings_data["findings"] if f["control_id"] not in controls]
    if unknown:
        raise ValueError(f"findings reference unknown control id(s): {unknown}")

    summary = compute_summary(findings_data["findings"])
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

    REPORTS_DIR.mkdir(exist_ok=True)
    json_path = REPORTS_DIR / f"{subject}-{ts}.json"
    html_path = REPORTS_DIR / f"{subject}-{ts}.html"

    json_path.write_text(
        json.dumps({"subject": subject, "summary": summary, **findings_data}, indent=2),
        encoding="utf-8",
    )
    html_path.write_text(render_html(subject, findings_data, controls), encoding="utf-8")
    return json_path, html_path


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument("subject", help="e.g. portfolio-sync, do178c-build-test")
    args = parser.parse_args()
    json_path, html_path = write_report(args.subject)
    print(f"Wrote {json_path}")
    print(f"Wrote {html_path}")


if __name__ == "__main__":
    run()
